name: Android CI Build and Test

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request: # Also good to run on PRs to these branches
    branches:
      - master
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Popular distribution

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3 # Uses a well-maintained action
      # This action will automatically download and cache the necessary SDK components
      # It typically defaults to the latest stable command-line tools.
      # We can specify versions if needed, but often defaults are fine.
      # For build-tools and platform, it usually picks them up from the project's build.gradle.
      # However, explicitly setting them here ensures consistency if needed.
      # Ensure build.gradle specifies apiLevel 34 and buildToolsVersion "34.0.0"
      # For this subtask, let the action handle defaults, can refine if it fails.

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Run unit tests
      run: ./gradlew test

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error # Fail the workflow if the APK is not found
